In [2]:
import polars as pl
pl.Config.set_tbl_rows(20)
pl.Config.set_fmt_str_lengths(60)
pl.Config.set_tbl_width_chars(200)

polars.config.Config

In [3]:
df_container = pl.read_parquet("./renamed/container_clean.parquet")
df_field     = pl.read_parquet("./renamed/field_clean.parquet")
df_structure = pl.read_parquet("./renamed/structure_clean.parquet")
df_entt      = pl.read_parquet("./renamed/link_clean.parquet")
df_source    = pl.read_parquet("./renamed/source_clean.parquet")
df_usage     = pl.read_csv("./renamed/usage_clean.csv")

tables = {
    "source":    df_source,
    "container": df_container,
    "structure": df_structure,
    "field":     df_field,
    "link":      df_entt,
    "usage":     df_usage,
}

FileNotFoundError: The system cannot find the path specified. (os error 3): ./renamed/container_clean.parquet

In [6]:
print(f"{'Table':<15} {'Lignes':>8} {'Colonnes':>10} {'Nulls total':>14} {'Str cols':>10} {'Num cols':>10}")
for name, df in tables.items():
    n_rows    = df.shape[0]
    n_cols    = df.shape[1]
    n_nulls   = sum(df[c].null_count() for c in df.columns)
    n_str     = sum(1 for c in df.columns if df[c].dtype == pl.Utf8)
    n_num     = sum(1 for c in df.columns if df[c].dtype in (pl.Int64, pl.Float64, pl.Int32))
    print(f"{name:<15} {n_rows:>8} {n_cols:>10} {n_nulls:>14} {n_str:>10} {n_num:>10}")

Table             Lignes   Colonnes    Nulls total   Str cols   Num cols
source               543         28           1042         21          2
container          19467         27         152600         20          2
structure         328159         39        2620631         26          2
field            2082956         43        8200399         28          3
link              641100         17         641163         15          1
usage              95315         92        4699410         75         12

In [7]:
for name, df in tables.items():
    print(f" {name.upper()}")
    display(df.head())

 SOURCE

shape: (5, 28)
┌─────────────┬─────────────────────────────────────────┬────────────────────────────────────────┬──────────────────────────────────────┬───┬───────────┬───────────┬─────────────────┬────────────────┐
│ export_date ┆ workspace_id                            ┆ node_id                                ┆ version_id                           ┆ … ┆ tech_code ┆ train_app ┆ hierarchy_level ┆ hierarchy_name │
│ ---         ┆ ---                                     ┆ ---                                    ┆ ---                                  ┆   ┆ ---       ┆ ---       ┆ ---             ┆ ---            │
│ date        ┆ str                                     ┆ str                                    ┆ str                                  ┆   ┆ str       ┆ str       ┆ i32             ┆ str            │
╞═════════════╪═════════════════════════════════════════╪════════════════════════════════════════╪══════════════════════════════════════╪═══╪═══════════╪═══════════╪═════════════════╪════════════════╡
│ 2026-03-06  ┆ 59f37279-3a9e-4025-956c-088a0c8f217d:59 ┆ 59f37279-3a9e-4025-956c-088a0c8f217d:4 ┆ 7333a87f-1f0f-4cc7-8d81-fcc2b283d433 ┆ … ┆           ┆           ┆ 1               ┆ Source         │
│             ┆ f37279-3a9e-4025-956c…                  ┆ df73410-8ea4-4273-affd…                ┆                                      ┆   ┆           ┆           ┆                 ┆                │
│ 2026-03-06  ┆ 59f37279-3a9e-4025-956c-088a0c8f217d:59 ┆ 59f37279-3a9e-4025-956c-088a0c8f217d:f ┆ 7333a87f-1f0f-4cc7-8d81-fcc2b283d433 ┆ … ┆           ┆           ┆ 1               ┆ Source         │
│             ┆ f37279-3a9e-4025-956c…                  ┆ 5e6b0ed-7e92-4601-8c7d…                ┆                                      ┆   ┆           ┆           ┆                 ┆                │
│ 2026-03-06  ┆ 59f37279-3a9e-4025-956c-088a0c8f217d:59 ┆ 59f37279-3a9e-4025-956c-088a0c8f217d:7 ┆ 7333a87f-1f0f-4cc7-8d81-fcc2b283d433 ┆ … ┆           ┆           ┆ 1               ┆ Source         │
│             ┆ f37279-3a9e-4025-956c…                  ┆ 456066c-42b1-473e-91c3…                ┆                                      ┆   ┆           ┆           ┆                 ┆                │
│ 2026-03-06  ┆ 59f37279-3a9e-4025-956c-088a0c8f217d:59 ┆ 59f37279-3a9e-4025-956c-088a0c8f217d:9 ┆ 7333a87f-1f0f-4cc7-8d81-fcc2b283d433 ┆ … ┆           ┆           ┆ 1               ┆ Source         │
│             ┆ f37279-3a9e-4025-956c…                  ┆ 3e37d9d-7ac0-45b3-8769…                ┆                                      ┆   ┆           ┆           ┆                 ┆                │
│ 2026-03-06  ┆ 59f37279-3a9e-4025-956c-088a0c8f217d:59 ┆ 59f37279-3a9e-4025-956c-088a0c8f217d:9 ┆ 7333a87f-1f0f-4cc7-8d81-fcc2b283d433 ┆ … ┆           ┆           ┆ 1               ┆ Source         │
│             ┆ f37279-3a9e-4025-956c…                  ┆ 98db59e-1fcc-4653-87d8…                ┆                                      ┆   ┆           ┆           ┆                 ┆                │
└─────────────┴─────────────────────────────────────────┴────────────────────────────────────────┴──────────────────────────────────────┴───┴───────────┴───────────┴─────────────────┴────────────────┘

 CONTAINER

shape: (5, 27)
┌─────────────┬─────────────────────────────────────┬─────────────────────────────────────┬────────────────────────────────────┬───┬─────────────┬──────────────────┬─────────────────┬────────────────┐
│ export_date ┆ workspace_id                        ┆ node_id                             ┆ version_id                         ┆ … ┆ parent_type ┆ parent_data_type ┆ hierarchy_level ┆ hierarchy_name │
│ ---         ┆ ---                                 ┆ ---                                 ┆ ---                                ┆   ┆ ---         ┆ ---              ┆ ---             ┆ ---            │
│ date        ┆ str                                 ┆ str                                 ┆ str                                ┆   ┆ str         ┆ str              ┆ i32             ┆ str            │
╞═════════════╪═════════════════════════════════════╪═════════════════════════════════════╪════════════════════════════════════╪═══╪═════════════╪══════════════════╪═════════════════╪════════════════╡
│ null        ┆ 59f37279-3a9e-4025-956c-088a0c8f217 ┆ 59f37279-3a9e-4025-956c-088a0c8f217 ┆ 7333a87f-1f0f-4cc7-8d81-fcc2b283d4 ┆ … ┆ Directory   ┆ Container        ┆ 2               ┆ Container      │
│             ┆ d:59f37279-3a9e-4025-956c…          ┆ d:053dacd0-b9f8-494c-a3a9…          ┆ 33                                 ┆   ┆             ┆                  ┆                 ┆                │
│ null        ┆ 59f37279-3a9e-4025-956c-088a0c8f217 ┆ 59f37279-3a9e-4025-956c-088a0c8f217 ┆ 7333a87f-1f0f-4cc7-8d81-fcc2b283d4 ┆ … ┆ Directory   ┆ Container        ┆ 2               ┆ Container      │
│             ┆ d:59f37279-3a9e-4025-956c…          ┆ d:17ec4c4a-e752-4b08-9ea8…          ┆ 33                                 ┆   ┆             ┆                  ┆                 ┆                │
│ null        ┆ 59f37279-3a9e-4025-956c-088a0c8f217 ┆ 59f37279-3a9e-4025-956c-088a0c8f217 ┆ 7333a87f-1f0f-4cc7-8d81-fcc2b283d4 ┆ … ┆ Directory   ┆ Container        ┆ 2               ┆ Container      │
│             ┆ d:59f37279-3a9e-4025-956c…          ┆ d:3d605460-05d6-4adf-8a9c…          ┆ 33                                 ┆   ┆             ┆                  ┆                 ┆                │
│ null        ┆ 59f37279-3a9e-4025-956c-088a0c8f217 ┆ 59f37279-3a9e-4025-956c-088a0c8f217 ┆ 7333a87f-1f0f-4cc7-8d81-fcc2b283d4 ┆ … ┆ NoSql       ┆ Source           ┆ 2               ┆ Container      │
│             ┆ d:59f37279-3a9e-4025-956c…          ┆ d:51f64341-6ec4-4abc-a9b7…          ┆ 33                                 ┆   ┆             ┆                  ┆                 ┆                │
│ null        ┆ 59f37279-3a9e-4025-956c-088a0c8f217 ┆ 59f37279-3a9e-4025-956c-088a0c8f217 ┆ 7333a87f-1f0f-4cc7-8d81-fcc2b283d4 ┆ … ┆ Directory   ┆ Container        ┆ 2               ┆ Container      │
│             ┆ d:59f37279-3a9e-4025-956c…          ┆ d:5cbf2e5a-768b-47cd-b191…          ┆ 33                                 ┆   ┆             ┆                  ┆                 ┆                │
└─────────────┴─────────────────────────────────────┴─────────────────────────────────────┴────────────────────────────────────┴───┴─────────────┴──────────────────┴─────────────────┴────────────────┘

 STRUCTURE

shape: (5, 39)
┌─────────────┬────────────────────────────────┬───────────────────────────────┬───────────────────────────────┬───┬───────────────────────────────┬────────────────┬─────────────────┬────────────────┐
│ export_date ┆ workspace_id                   ┆ node_id                       ┆ version_id                    ┆ … ┆ kafka_schema_registry_complia ┆ is_kafka_topic ┆ hierarchy_level ┆ hierarchy_name │
│ ---         ┆ ---                            ┆ ---                           ┆ ---                           ┆   ┆ nt                            ┆ ---            ┆ ---             ┆ ---            │
│ date        ┆ str                            ┆ str                           ┆ str                           ┆   ┆ ---                           ┆ bool           ┆ i32             ┆ str            │
│             ┆                                ┆                               ┆                               ┆   ┆ str                           ┆                ┆                 ┆                │
╞═════════════╪════════════════════════════════╪═══════════════════════════════╪═══════════════════════════════╪═══╪═══════════════════════════════╪════════════════╪═════════════════╪════════════════╡
│ 2026-03-06  ┆ 59f37279-3a9e-4025-956c-088a0c ┆ 59f37279-3a9e-4025-956c-088a0 ┆ 7333a87f-1f0f-4cc7-8d81-fcc2b ┆ … ┆ Non contrôlé                  ┆ false          ┆ 3               ┆ Structure      │
│             ┆ 8f217d:59f37279-3a9e-4025-956c ┆ c8f217d:14d476d5-5b23-407c-bc ┆ 283d433                       ┆   ┆                               ┆                ┆                 ┆                │
│             ┆ …                              ┆ 3d…                           ┆                               ┆   ┆                               ┆                ┆                 ┆                │
│ 2026-03-06  ┆ 59f37279-3a9e-4025-956c-088a0c ┆ 59f37279-3a9e-4025-956c-088a0 ┆ 7333a87f-1f0f-4cc7-8d81-fcc2b ┆ … ┆ Non contrôlé                  ┆ false          ┆ 3               ┆ Structure      │
│             ┆ 8f217d:59f37279-3a9e-4025-956c ┆ c8f217d:14ff8253-4c7e-4274-bb ┆ 283d433                       ┆   ┆                               ┆                ┆                 ┆                │
│             ┆ …                              ┆ a5…                           ┆                               ┆   ┆                               ┆                ┆                 ┆                │
│ 2026-03-06  ┆ 59f37279-3a9e-4025-956c-088a0c ┆ 59f37279-3a9e-4025-956c-088a0 ┆ 7333a87f-1f0f-4cc7-8d81-fcc2b ┆ … ┆ Non contrôlé                  ┆ false          ┆ 3               ┆ Structure      │
│             ┆ 8f217d:59f37279-3a9e-4025-956c ┆ c8f217d:151ed6c6-1e95-4366-a9 ┆ 283d433                       ┆   ┆                               ┆                ┆                 ┆                │
│             ┆ …                              ┆ 5f…                           ┆                               ┆   ┆                               ┆                ┆                 ┆                │
│ 2026-03-06  ┆ 59f37279-3a9e-4025-956c-088a0c ┆ 59f37279-3a9e-4025-956c-088a0 ┆ 7333a87f-1f0f-4cc7-8d81-fcc2b ┆ … ┆ Non contrôlé                  ┆ false          ┆ 3               ┆ Structure      │
│             ┆ 8f217d:59f37279-3a9e-4025-956c ┆ c8f217d:152490e6-6fc8-4044-83 ┆ 283d433                       ┆   ┆                               ┆                ┆                 ┆                │
│             ┆ …                              ┆ 5e…                           ┆                               ┆   ┆                               ┆                ┆                 ┆                │
│ 2026-03-06  ┆ 59f37279-3a9e-4025-956c-088a0c ┆ 59f37279-3a9e-4025-956c-088a0 ┆ 7333a87f-1f0f-4cc7-8d81-fcc2b ┆ … ┆ Non contrôlé                  ┆ false          ┆ 3               ┆ Structure      │
│             ┆ 8f217d:59f37279-3a9e-4025-956c ┆ c8f217d:1530f505-1129-477a-ae ┆ 283d433                       ┆   ┆                               ┆                ┆                 ┆                │
│             ┆ …                              ┆ 60…                           ┆                               ┆   ┆                               ┆                ┆                 ┆                │
└─────────────┴────────────────────────────────┴───────────────────────────────┴───────────────────────────────┴───┴───────────────────────────────┴────────────────┴─────────────────┴────────────────┘

 FIELD

shape: (5, 43)
┌─────────────┬──────────────────────────────────┬─────────────────────────────────┬─────────────────────────────────┬───┬──────────────────┬───────────────────────┬─────────────────┬────────────────┐
│ export_date ┆ workspace_id                     ┆ node_id                         ┆ version_id                      ┆ … ┆ is_golden_source ┆ governance_risk_score ┆ hierarchy_level ┆ hierarchy_name │
│ ---         ┆ ---                              ┆ ---                             ┆ ---                             ┆   ┆ ---              ┆ ---                   ┆ ---             ┆ ---            │
│ date        ┆ str                              ┆ str                             ┆ str                             ┆   ┆ bool             ┆ i32                   ┆ i32             ┆ str            │
╞═════════════╪══════════════════════════════════╪═════════════════════════════════╪═════════════════════════════════╪═══╪══════════════════╪═══════════════════════╪═════════════════╪════════════════╡
│ 2026-03-06  ┆ 59f37279-3a9e-4025-956c-088a0c8f ┆                                 ┆                                 ┆ … ┆ null             ┆ 0                     ┆ 4               ┆ Field          │
│             ┆ 217d:59f37279-3a9e-4025-956c…    ┆                                 ┆                                 ┆   ┆                  ┆                       ┆                 ┆                │
│ 2026-03-06  ┆ 59f37279-3a9e-4025-956c-088a0c8f ┆                                 ┆                                 ┆ … ┆ null             ┆ 0                     ┆ 4               ┆ Field          │
│             ┆ 217d:59f37279-3a9e-4025-956c…    ┆                                 ┆                                 ┆   ┆                  ┆                       ┆                 ┆                │
│ 2026-03-06  ┆ 59f37279-3a9e-4025-956c-088a0c8f ┆ 59f37279-3a9e-4025-956c-088a0c8 ┆ 7333a87f-1f0f-4cc7-8d81-fcc2b28 ┆ … ┆ false            ┆ 0                     ┆ 4               ┆ Field          │
│             ┆ 217d:59f37279-3a9e-4025-956c…    ┆ f217d:1dab9051-0598-47f0-a148…  ┆ 3d433                           ┆   ┆                  ┆                       ┆                 ┆                │
│ 2026-03-06  ┆ 59f37279-3a9e-4025-956c-088a0c8f ┆ 59f37279-3a9e-4025-956c-088a0c8 ┆ 7333a87f-1f0f-4cc7-8d81-fcc2b28 ┆ … ┆ false            ┆ 0                     ┆ 4               ┆ Field          │
│             ┆ 217d:59f37279-3a9e-4025-956c…    ┆ f217d:70067f2a-698b-4de8-8c2d…  ┆ 3d433                           ┆   ┆                  ┆                       ┆                 ┆                │
│ 2026-03-06  ┆ 59f37279-3a9e-4025-956c-088a0c8f ┆ 59f37279-3a9e-4025-956c-088a0c8 ┆ 7333a87f-1f0f-4cc7-8d81-fcc2b28 ┆ … ┆ false            ┆ 1                     ┆ 4               ┆ Field          │
│             ┆ 217d:59f37279-3a9e-4025-956c…    ┆ f217d:700ee016-d7cb-4041-bcbb…  ┆ 3d433                           ┆   ┆                  ┆                       ┆                 ┆                │
└─────────────┴──────────────────────────────────┴─────────────────────────────────┴─────────────────────────────────┴───┴──────────────────┴───────────────────────┴─────────────────┴────────────────┘

 LINK

shape: (5, 17)
┌─────────────┬─────────────────────────────┬─────────────────────────────┬─────────────────────────┬───┬─────────────────────────────┬─────────────────────────────┬─────────────────┬────────────────┐
│ export_date ┆ workspace_id                ┆ src_node_id                 ┆ src_name_label          ┆ … ┆ tgt_path_type               ┆ tgt_path                    ┆ hierarchy_level ┆ hierarchy_name │
│ ---         ┆ ---                         ┆ ---                         ┆ ---                     ┆   ┆ ---                         ┆ ---                         ┆ ---             ┆ ---            │
│ date        ┆ str                         ┆ str                         ┆ str                     ┆   ┆ str                         ┆ str                         ┆ i32             ┆ str            │
╞═════════════╪═════════════════════════════╪═════════════════════════════╪═════════════════════════╪═══╪═════════════════════════════╪═════════════════════════════╪═════════════════╪════════════════╡
│ null        ┆ 59f37279-3a9e-4025-956c-088 ┆ 59f37279-3a9e-4025-956c-088 ┆ dissolutionDecisionDate ┆ … ┆ \Universe\Universe\Universe ┆ \Modèle Objets Métier -     ┆ 0               ┆ Link           │
│             ┆ a0c8f217d:59f37279-3a9e-402 ┆ a0c8f217d:363a0c7a-541c-4dd ┆                         ┆   ┆ \Concept\BusinessTerm       ┆ MOM\Tiers\Données           ┆                 ┆                │
│             ┆ 5-956c…                     ┆ 2-9d8b…                     ┆                         ┆   ┆                             ┆ descriptives spéci…         ┆                 ┆                │
│ null        ┆ 59f37279-3a9e-4025-956c-088 ┆ 59f37279-3a9e-4025-956c-088 ┆ Date creation recording ┆ … ┆ \Universe\Universe\Universe ┆ \Modèle Objets Métier - MOM ┆ 0               ┆ Link           │
│             ┆ a0c8f217d:59f37279-3a9e-402 ┆ a0c8f217d:fb220d73-1d96-4ec ┆                         ┆   ┆ \Universe\BusinessTerm      ┆ \Contrat\Caractéristiques   ┆                 ┆                │
│             ┆ 5-956c…                     ┆ 3-9227…                     ┆                         ┆   ┆                             ┆ général…                    ┆                 ┆                │
│ null        ┆ 59f37279-3a9e-4025-956c-088 ┆ 59f37279-3a9e-4025-956c-088 ┆ Date position           ┆ … ┆ \Universe\Universe\Universe ┆ \Modèle Objets Métier -     ┆ 0               ┆ Link           │
│             ┆ a0c8f217d:59f37279-3a9e-402 ┆ a0c8f217d:e9d8f166-b879-404 ┆                         ┆   ┆ \Universe\BusinessTerm      ┆ MOM\Contrat\Informations de ┆                 ┆                │
│             ┆ 5-956c…                     ┆ c-8425…                     ┆                         ┆   ┆                             ┆ gestion\…                   ┆                 ┆                │
│ null        ┆ 59f37279-3a9e-4025-956c-088 ┆ 59f37279-3a9e-4025-956c-088 ┆ Date de dernier dépôt   ┆ … ┆ \Universe\Universe\Business ┆ \Modèle Objets Métier -     ┆ 0               ┆ Link           │
│             ┆ a0c8f217d:59f37279-3a9e-402 ┆ a0c8f217d:84eb5245-5770-4e2 ┆ Bilan Final             ┆   ┆ Term                        ┆ MOM\Evénements\Date d'effet ┆                 ┆                │
│             ┆ 5-956c…                     ┆ d-9084…                     ┆                         ┆   ┆                             ┆ de l'évé…                   ┆                 ┆                │
│ null        ┆ 59f37279-3a9e-4025-956c-088 ┆ 59f37279-3a9e-4025-956c-088 ┆ Date phase              ┆ … ┆ \Universe\Universe\Universe ┆ \Modèle Objets Métier -     ┆ 0               ┆ Link           │
│             ┆ a0c8f217d:59f37279-3a9e-402 ┆ a0c8f217d:683e1ef8-4d14-4d5 ┆                         ┆   ┆ \Universe\BusinessTerm      ┆ MOM\Contrat\Informations de ┆                 ┆                │
│             ┆ 5-956c…                     ┆ b-8397…                     ┆                         ┆   ┆                             ┆ gestion\…                   ┆                 ┆                │
└─────────────┴─────────────────────────────┴─────────────────────────────┴─────────────────────────┴───┴─────────────────────────────┴─────────────────────────────┴─────────────────┴────────────────┘

 USAGE

shape: (5, 92)
┌─────────────────────────────┬─────────────────────────────┬─────────────────────────────┬─────────────────────────────┬───┬──────────────────────┬─────────────────┬────────────────┬────────────────┐
│ usage_uuid                  ┆ usage_name                  ┆ usage_tech_name             ┆ usage_path                  ┆ … ┆ usage_quality_status ┆ hierarchy_level ┆ hierarchy_name ┆ source_file    │
│ ---                         ┆ ---                         ┆ ---                         ┆ ---                         ┆   ┆ ---                  ┆ ---             ┆ ---            ┆ ---            │
│ str                         ┆ str                         ┆ str                         ┆ str                         ┆   ┆ str                  ┆ i64             ┆ str            ┆ str            │
╞═════════════════════════════╪═════════════════════════════╪═════════════════════════════╪═════════════════════════════╪═══╪══════════════════════╪═════════════════╪════════════════╪════════════════╡
│ 59f37279-3a9e-4025-956c-088 ┆ KQI_RET_Ecart_PM_BCPRET_COH ┆ KQI_RET_Ecart_PM_BCPRET_COH ┆ \Usages opérationnels\RET : ┆ … ┆ Critical             ┆ 0               ┆ Usage          ┆ usag_usage.csv │
│ a0c8f217d:9fbe1468-e8c2-4d2 ┆                             ┆                             ┆ Référentiel Tiers -         ┆   ┆                      ┆                 ┆                ┆                │
│ d-9411…                     ┆                             ┆                             ┆ RET\Contrôle…               ┆   ┆                      ┆                 ┆                ┆                │
│ 59f37279-3a9e-4025-956c-088 ┆ Devise principale           ┆ Devise principale           ┆ \Usages opérationnels\CLI : ┆ … ┆ Critical             ┆ 0               ┆ Usage          ┆ usag_usage.csv │
│ a0c8f217d:89bfdf5a-70d6-41d ┆                             ┆                             ┆ Comptoir                    ┆   ┆                      ┆                 ┆                ┆                │
│ e-8309…                     ┆                             ┆                             ┆ Client\Tiers\Données de…    ┆   ┆                      ┆                 ┆                ┆                │
│ 59f37279-3a9e-4025-956c-088 ┆ Taxe                        ┆ Taxe                        ┆ \Usages opérationnels\PRT : ┆ … ┆ Critical             ┆ 0               ┆ Usage          ┆ usag_usage.csv │
│ a0c8f217d:b4bbb9e8-0860-41e ┆                             ┆                             ┆ Cassiopae                   ┆   ┆                      ┆                 ┆                ┆                │
│ 4-b5f8…                     ┆                             ┆                             ┆ Web\Dossiers\Rubriques…     ┆   ┆                      ┆                 ┆                ┆                │
│ 59f37279-3a9e-4025-956c-088 ┆ TauxDeMixage                ┆ mixing_rate                 ┆ \Dictionnaire des           ┆ … ┆ Critical             ┆ 0               ┆ Usage          ┆ usag_usage.csv │
│ a0c8f217d:0fdd26cc-b4f3-493 ┆                             ┆                             ┆ Ontologies\2. Topics        ┆   ┆                      ┆                 ┆                ┆                │
│ 4-8eb1…                     ┆                             ┆                             ┆ Fonctionnels\Topics E…      ┆   ┆                      ┆                 ┆                ┆                │
│ 59f37279-3a9e-4025-956c-088 ┆ Statut                      ┆ Statut                      ┆ \Usages opérationnels\OGS : ┆ … ┆ Critical             ┆ 0               ┆ Usage          ┆ usag_usage.csv │
│ a0c8f217d:e683f3ba-dac2-46a ┆                             ┆                             ┆ Gestion de                  ┆   ┆                      ┆                 ┆                ┆                │
│ 7-8019…                     ┆                             ┆                             ┆ stock\Réceptions\Lign…      ┆   ┆                      ┆                 ┆                ┆                │
└─────────────────────────────┴─────────────────────────────┴─────────────────────────────┴─────────────────────────────┴───┴──────────────────────┴─────────────────┴────────────────┴────────────────┘